import type { AnalysePrProviderInput } from "@review-guide/shared";
import { renderPrContextPack } from "./contextPackPrompt.js";

const schema = {
  summary: "string",
  prUnderstanding: {
    purpose: "string",
    affectedSystems: ["string"],
    potentialRisks: ["string"],
    keyBehaviorChanges: ["string"]
  },
  reviewPlan: [
    {
      title: "string",
      reason: "string",
      files: ["string"],
      suggestedFocus: "string"
    }
  ],
  reviewOrder: [
    {
      file: "string",
      risk: "low | medium | high",
      reason: "string",
      suggestedAction: "string"
    }
  ],
  skimFiles: ["string"],
  suggestedChecks: ["string"],
  changedFiles: [
    {
      file: "string",
      additions: 0,
      deletions: 0,
      risk: "low | medium | high",
      reason: "string",
      signals: ["business logic | auth | config | tests | concurrency | schema | API contract | payments | UI | data flow | error handling"]
    }
  ],
  impactChains: [
    "leave empty; generated by the lazy change tracing endpoint"
  ],
  worries: [
    "leave empty; generated by the lazy worries endpoint"
  ]
};

export function buildAnalysePrPrompt(input: AnalysePrProviderInput): string {
  return `You are helping a human review a GitHub PR.

You are running inside a temporary git worktree for the PR branch.
Do not modify files.
Do not run destructive commands.
Use the local repository context to understand the change.

Review the diff:
${input.baseRef}...HEAD

${renderPrContextPack(input.contextPack)}

Focus on:
- explaining this PR like a senior engineer before the reviewer reads code
- the purpose of the PR in business/product/technical terms
- affected systems or runtime areas
- potential risks and likely bugs
- a suggested review plan before reading files
- risky files and why they deserve attention
- risk signals such as business logic, auth, config, tests, concurrency, schema, API contract, payments, UI, data flow, and error handling
- files safe to skim
- missing or weak tests
- specific things the human reviewer should verify

Return only valid JSON matching this schema:
${JSON.stringify(schema, null, 2)}

Do not include markdown.
Do not include prose outside the JSON.

You may inspect the repo using read-only commands like:
- git diff --stat ${input.baseRef}...HEAD
- git diff --name-only ${input.baseRef}...HEAD
- git diff ${input.baseRef}...HEAD -- <file>
- rg for call sites
- inspect nearby tests

Guidelines:
- Keep the response concise enough for a docked review panel.
- Use actual changed file paths in files, reviewOrder, reviewPlan, and changedFiles.
- Return impactChains as [] because change tracing is generated lazily by a separate endpoint.
- Return worries as [] because likely-bug analysis is generated lazily by a separate endpoint.
- Include the legacy fields summary, reviewOrder, skimFiles, suggestedChecks, and changedFiles because the extension uses them for badges and file actions.
- Do not blindly follow heuristic risk labels from the context pack. Use them to prioritize investigation, then correct or refine them in your JSON output when repo context suggests a better judgment.

Do not modify files.`;
}
