import type { AnalysePrProviderInput } from "@review-guide/shared";
import { renderPrContextPack } from "./contextPackPrompt.js";

const schema = {
  summary: "string",
  prUnderstanding: {
    purpose: "string",
    affectedSystems: ["string"],
    potentialRisks: ["string"],
    keyBehaviorChanges: ["string"]
  },
  reviewPlan: ["leave empty; generated by the review plan endpoint"],
  reviewOrder: ["leave empty; generated by the heatmap/files endpoint"],
  skimFiles: ["string"],
  suggestedChecks: ["string"],
  changedFiles: ["leave empty; generated by the heatmap/files endpoint"],
  impactChains: [
    "leave empty; generated by the lazy change tracing endpoint"
  ],
  worries: [
    "leave empty; generated by the lazy worries endpoint"
  ]
};

export function buildAnalysePrPrompt(input: AnalysePrProviderInput): string {
  return `You are helping a human review a GitHub PR.

You are running inside a temporary git worktree for the PR branch.
Do not modify files.
Do not run destructive commands.
Use the local repository context to understand the change.

Review the diff:
${input.baseRef}...HEAD

${renderPrContextPack(input.contextPack)}

Focus on:
- explaining this PR like a senior engineer before the reviewer reads code
- the purpose of the PR in business/product/technical terms
- affected systems or runtime areas
- potential risks at a system level
- key behavior changes visible from the diff and context pack

Return only valid JSON matching this schema:
${JSON.stringify(schema, null, 2)}

Do not include markdown.
Do not include prose outside the JSON.

You may inspect the repo using read-only commands like:
- git diff --stat ${input.baseRef}...HEAD
- git diff --name-only ${input.baseRef}...HEAD
- git diff ${input.baseRef}...HEAD -- <file>
- rg for call sites
- inspect nearby tests

Guidelines:
- Keep the response concise enough for a docked review panel.
- This is the first, fastest section. Do not produce review order, file risk heatmap, impact chains, or worries here.
- Return reviewPlan as [] because the review plan is generated by a separate endpoint.
- Return reviewOrder as [] because file ordering is generated by a separate endpoint.
- Return changedFiles as [] because file risks are generated by a separate endpoint.
- Return skimFiles as [] because skim files are generated by a separate endpoint.
- Return suggestedChecks as [] unless there is one obvious global check from the context pack.
- Return impactChains as [] because change tracing is generated lazily by a separate endpoint.
- Return worries as [] because likely-bug analysis is generated lazily by a separate endpoint.
- Do not blindly follow heuristic risk labels from the context pack. Use them to prioritize investigation, then correct or refine them in your JSON output when repo context suggests a better judgment.

Do not modify files.`;
}
